<?php
require_once 'config/database.php';
require_once 'config/functions.php';
$id = sanitize($_GET['id'] ?? 0);
$product = fetchSingleData("SELECT * FROM produk WHERE id = '$id'");
if (!$product) { redirect('katalog.php'); }
$colors = fetchData("SELECT warna FROM warna_produk WHERE produk_id = '$id' ORDER BY id ASC");
$settings = fetchSingleData("SELECT * FROM pengaturan LIMIT 1") ?: ['nama_perusahaan' => 'Lepoir', 'whatsapp' => ''];
$whatsapp = preg_replace('/[^0-9]/', '', $settings['whatsapp'] ?? '');
$message = rawurlencode('Halo, saya tertarik memesan ' . $product['nama']);
function colorHex($color) {
	$map = ['hitam'=>'#171717','black'=>'#171717','cokelat'=>'#7a4b2a','brunette'=>'#5c321e','copper'=>'#b87333','pirang'=>'#e5b94d','blonde'=>'#e5b94d','merah'=>'#c62828','burgundy'=>'#800020','ungu'=>'#7e3f98','biru'=>'#2563eb','navy'=>'#172554','pink'=>'#ec78a5','orange'=>'#ed8936','hijau'=>'#3f8f58','olive'=>'#71834b','abu-abu'=>'#94a3b8','grey'=>'#94a3b8','putih'=>'#f8fafc'];
	return $map[strtolower(trim($color))] ?? '#08abe5';
}
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?php echo htmlspecialchars($product['nama']); ?> - Katalog</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="catalog-page"><nav class="navbar navbar-dark sticky-top py-3"><div class="container"><a class="navbar-brand d-flex align-items-center" href="index.php"><?php if (!empty($settings['logo'])): ?><img src="<?php echo htmlspecialchars($settings['logo']); ?>" alt="Logo Lepoir" class="brand-mark me-2"><?php else: ?><i class="bi bi-droplet-half text-info me-2"></i><?php endif; ?><span>Lepoir</span></a><a href="katalog.php" class="btn btn-outline-light btn-sm"><i class="bi bi-arrow-left me-1"></i> Kembali</a></div></nav>
<main class="container py-5"><div class="row g-5 align-items-center"><div class="col-lg-6"><div class="detail-image"><?php if (!empty($product['gambar'])): ?><img src="<?php echo htmlspecialchars($product['gambar']); ?>" alt="<?php echo htmlspecialchars($product['nama']); ?>"><?php else: ?><i class="bi bi-image"></i><?php endif; ?></div></div><div class="col-lg-6"><span class="card-brand"><?php echo htmlspecialchars($product['merek']); ?></span><h1 class="display-5 fw-bold my-2"><?php echo htmlspecialchars($product['nama']); ?></h1><p class="card-price fs-3"><?php echo formatRupiah($product['harga']); ?></p><p class="lead text-secondary"><?php echo nl2br(htmlspecialchars($product['deskripsi'])); ?></p><h6 class="fw-bold mt-4">Pilihan warna</h6><div class="mb-4"><?php foreach ($colors as $color): ?><span class="badge badge-color fs-6 me-1 mb-1"><span class="color-dot" style="background: <?php echo colorHex($color['warna']); ?>"></span><?php echo htmlspecialchars($color['warna']); ?></span><?php endforeach; ?></div><?php if ($whatsapp): ?><a href="https://wa.me/<?php echo $whatsapp; ?>?text=<?php echo $message; ?>" target="_blank" class="btn btn-success btn-modern"><i class="bi bi-whatsapp me-2"></i>Pesan via WhatsApp</a><?php endif; ?></div></div></main>
<footer class="footer mt-5"><div class="container"><div class="row gy-4 align-items-center"><div class="col-md-6"><h4 class="fw-bold text-white mb-2">Lepoir</h4><p class="text-secondary mb-0">Warna rambut untuk mengekspresikan karakter Anda.</p></div><div class="col-md-6 text-md-end"><h6 class="fw-bold text-white mb-3">Jelajahi Lepoir</h6><p class="mb-0"><a class="footer-link" href="katalog.php">Katalog</a><a class="footer-link" href="warna.php">Panduan Warna</a><a class="footer-link" href="index.php#kontak">Kontak</a></p></div></div><hr class="my-4 border-secondary opacity-25"><div class="text-center text-secondary small">&copy; 2026 Lepoir. All Rights Reserved.</div></div></footer></body></html>
