<?php
require_once 'config/database.php';
require_once 'config/functions.php';
$settings = fetchSingleData("SELECT * FROM pengaturan LIMIT 1") ?: ['nama_perusahaan' => 'Lepoir', 'logo' => ''];
$colors = fetchData("SELECT wp.warna, COUNT(wp.produk_id) AS jumlah_produk FROM warna_produk wp GROUP BY wp.warna ORDER BY wp.warna ASC");
function colorHex($color) {
	$map = ['hitam'=>'#171717','black'=>'#171717','cokelat'=>'#7a4b2a','brunette'=>'#5c321e','copper'=>'#b87333','pirang'=>'#e5b94d','blonde'=>'#e5b94d','merah'=>'#c62828','burgundy'=>'#800020','ungu'=>'#7e3f98','biru'=>'#2563eb','navy'=>'#172554','pink'=>'#ec78a5','orange'=>'#ed8936','hijau'=>'#3f8f58','olive'=>'#71834b','abu-abu'=>'#94a3b8','grey'=>'#94a3b8','putih'=>'#f8fafc'];
	return $map[strtolower(trim($color))] ?? '#08abe5';
}
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Panduan Warna - Lepoir</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="catalog-page warna-page"><nav class="navbar navbar-dark sticky-top py-3"><div class="container"><a class="navbar-brand d-flex align-items-center" href="index.php"><?php if (!empty($settings['logo'])): ?><img src="<?php echo htmlspecialchars($settings['logo']); ?>" alt="Logo Lepoir" class="brand-mark me-2"><?php else: ?><i class="bi bi-droplet-half text-info me-2"></i><?php endif; ?><span>Lepoir</span></a><div><a class="nav-link d-inline-block" href="katalog.php">Katalog</a><a class="nav-link d-inline-block active" href="warna.php">Panduan Warna</a></div></div></nav>
<header class="catalog-header py-5"><div class="container"><span class="eyebrow">LEPOIR / COLOR GUIDE</span><h1 class="display-5 fw-bold mt-2">Pilih shade yang sesuai ceritamu</h1><p class="lead mb-0">Lihat pilihan warna yang tersedia dan temukan inspirasi untuk penampilan berikutnya.</p></div></header><main class="container py-5"><div class="shade-intro mb-4"><div class="info-icon"><i class="bi bi-palette"></i></div><div><p class="section-kicker mb-1">PALETTE LEPOIR</p><h2 class="h4 fw-bold mb-1">Satu warna, satu karakter.</h2><p class="text-muted mb-0">Kenali koleksi shade kami dan temukan warna yang paling cocok dengan gayamu.</p></div></div><div class="row g-3"><?php foreach ($colors as $color): ?><div class="col-6 col-md-4 col-lg-3"><div class="shade-card"><span class="large-color-dot" style="background: <?php echo colorHex($color['warna']); ?>"></span><h2><?php echo htmlspecialchars($color['warna']); ?></h2><p><i class="bi bi-droplet-half me-1"></i><?php echo (int)$color['jumlah_produk']; ?> produk tersedia</p></div></div><?php endforeach; ?></div></main>
<footer class="footer mt-5"><div class="container"><div class="row gy-4 align-items-center"><div class="col-md-6"><h4 class="fw-bold text-white mb-2">Lepoir</h4><p class="text-secondary mb-0">Temukan shade yang paling cocok dengan gayamu.</p></div><div class="col-md-6 text-md-end"><h6 class="fw-bold text-white mb-3">Jelajahi Lepoir</h6><p class="mb-0"><a class="footer-link" href="katalog.php">Katalog</a><a class="footer-link" href="warna.php">Panduan Warna</a><a class="footer-link" href="index.php#kontak">Kontak</a></p></div></div><hr class="my-4 border-secondary opacity-25"><div class="text-center text-secondary small">&copy; 2026 Lepoir. All Rights Reserved.</div></div></footer></body></html>
